{% set name = "Orange3-SingleCell" %}
{% set version = "1.6.0" %}
{% set sha256 = "dccce6cb63085fff3dc524e12325e9dfb6c415661dacc57454a27e21bb31341a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - html-index = orangecontrib.single_cell.widgets:WIDGET_HELP_PATH
    - Single Cell = orangecontrib.single_cell.widgets:main


requirements:
  host:
    - python >=3
    - pip
    - sphinx
    - recommonmark
    - setuptools
    - setuptools_scm
  run:
    - python >=3
    - orange3 >=3.34.0
    - orange3-bioinformatics >=4.0.0
    - fastdtw ==0.3.2
    - pandas >=0.23
    - loompy >=2.0.10
    - xlrd >=2.0.1
    - openpyxl
    - anndata >=0.6.21
    - numpy
    - scikit-learn

test:
  # Python imports
  imports:
    - orangecontrib.single_cell
    - orangecontrib.single_cell.widgets
    - orangecontrib.single_cell.preprocess

about:
  home: https://github.com/biolab/orange3-single-cell/
  license: GPL-3
  license_family: GPL
  license_file: LICENSE
  summary: Single-cell Orange

extra:
  recipe-maintainers:
    - jakakokosar
    - astaric
    - lanzagar
    - ales-erjavec
    - VesnaT
    - primozgodec
