{% set name = "Orange3-SingleCell" %}
{% set version = "1.1.0" %}
{% set sha256 = "1a90e19cb118823238cca28f69ea305bccc37e7c1d04f7a7cf39755d18c02ce0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - vcftutorials = orangecontrib.single_cell.tutorials:main
    - html-index = orangecontrib.single_cell.widgets:WIDGET_HELP_PATH
    - Single Cell = orangecontrib.single_cell.widgets:main

    
requirements:
  host:
    - python >=3
    - pip 
    - sphinx
    - recommonmark
    - setuptools
  run:
    - python >=3
    - orange3
    - orange3-bioinformatics
    - pandas
    - fastdtw
    - loompy
    - networkx
    - anndata

test:
  # Python imports
  imports:
    - orangecontrib.single_cell
    - orangecontrib.single_cell.__main__
    - orangecontrib.single_cell.widgets
    - orangecontrib.single_cell.preprocess
    - orangecontrib.single_cell.tutorials
  commands:
    - python -m orangecontrib.single_cell --help

about:
  home: https://singlecell.biolab.si/
  license: GPL-3
  license_family: GPL
  license_file: LICENSE
  summary: 'Single-cell Orange'

extra:
  recipe-maintainers:
    - jakakokosar
    - astaric
    - lanzagar
    - ales-erjavec
